service: aws-python-line-api
provider:
  name: aws
  runtime: python3.7
  region: ${env:REGION}
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - ${env:SQS_ARN}
functions:
  line_notify:
    handler: consumer/notify_handler.line_notify_handler
    events:
      - sqs: ${env:SQS_ARN}

  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
custom:
  wsgi:
    app: api.app
  pythonRequirements:
    dockerizePip: true
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-dotenv-plugin
